In [37]:
import sys
import os
import numpy as np
import random as rd
import networkx as nx
import matplotlib.pyplot as plt


os.sys.path.append('/Users/smula/Documents/projects/Networkx/modularity-density/ModularityDensity')
#from fine_tuned_qds_sparse_test import *
from fine_tuned_modularity import *
from fine_tuned_modularity_density import *
from metrics import *

# Karate Club

In [38]:
G = nx.karate_club_graph()
adj = nx.to_scipy_sparse_matrix(G)

array([2, 2, 2, 2, 4, 4, 4, 2, 3, 3, 4, 2, 2, 2, 3, 3, 4, 2, 3, 2, 3, 2,
       3, 1, 1, 1, 3, 1, 1, 3, 3, 1, 3, 3])

In [45]:
#Test Normalized Fine-tuned-Modularity density
c = fine_tuned_clustering_qds(G, seed = 100)
modularity_density(adj, c, np.unique(c))

0.23126500169457212

In [47]:
# Test Normalize
c = fine_tuned_clustering_qds(G, normalize = False, seed = 100)
modularity_density(adj, c, np.unique(c))

0.23821951467671487

In [49]:
#Test method tracemin
c = fine_tuned_clustering_qds(G, evd_method='tracemin', seed = 100)
modularity_density(adj, c, np.unique(c))

0.23126500169457212

In [50]:
#Test method lobpcg
c = fine_tuned_clustering_qds(G, evd_method='lobpcg', seed = 100)
modularity_density(adj, c, np.unique(c))

0.2312650016945721

In [53]:
#Test tolerence
c = fine_tuned_clustering_qds(G, tolerence=1e-04, seed = 100)
modularity_density(adj, c, np.unique(c))

0.2312650016945721

In [54]:
#Test seed
c = fine_tuned_clustering_qds(G, seed = 2)
modularity_density(adj, c, np.unique(c))

0.23126500169457212

In [69]:
#Test Whole new modularity
c = fine_tuned_clustering_qds(G, normalize=False, evd_method='lobpcg', seed=2)
modularity_density(adj, c, np.unique(c))

0.23821951467671487

In [56]:
#Test UnNormalized Fine-tuned-Modularity
c = fine_tuned_clustering_q(G, normalize = False, seed = 100)
modularity_r(adj, c, np.unique(c))

0.4197896120973045

In [57]:
#Test Normalized Fine-tuned-Modularity
c = fine_tuned_clustering_q(G, seed = 100)
modularity_r(adj, c, np.unique(c))

0.4197896120973044

In [59]:
#Test method tracemin
c = fine_tuned_clustering_q(G, evd_method='tracemin', seed = 100)
modularity_r(adj, c, np.unique(c))

0.41978961209730437

In [65]:
#Test method lobpcg
c = fine_tuned_clustering_q(G, evd_method='lobpcg', seed = 100)
modularity_r(adj, c, np.unique(c))

0.4197896120973044

In [61]:
#Test tolerence
c = fine_tuned_clustering_q(G, tolerence=1e-04, seed = 100)
modularity_r(adj, c, np.unique(c))

0.4197896120973044

In [62]:
#Test seed
c = fine_tuned_clustering_q(G, seed = 2)
modularity_r(adj, c, np.unique(c))

0.41978961209730437

In [66]:
#Test r
c = fine_tuned_clustering_q(G, r=2, seed = 100)
modularity_r(adj, c, np.unique(c), r=2)

0.5148278061224489

In [68]:
#Test Whole new modularity
c = fine_tuned_clustering_q(G, normalize=False, r=2, evd_method='lobpcg', seed=2)
modularity_r(adj, c, np.unique(c), r=2)

0.5153459821428571

In [26]:
modularity_r(adj, c, [1, 2])

0.21301775147928995

In [32]:
modularity_density(adj, c, [1, 2])

0.12381147180972354

In [31]:
modularity_density(adj, c, np.array([1, 2]))

0.12381147180972354

In [30]:
modularity_density(adj, c, np.unique(c))

0.23018976296948324

In [45]:
import timeit

start_time = timeit.default_timer()

[1]

end_time = timeit.default_timer() - start_time
print(end_time)

4.056799934915034e-05


In [67]:
start_time = timeit.default_timer()
nx.to_scipy_sparse_matrix(G)
end_time = timeit.default_timer() - start_time
print(end_time)

0.001186283000606636


In [65]:
start_time = timeit.default_timer()
nx.from_scipy_sparse_matrix(adj)
end_time = timeit.default_timer() - start_time
print(end_time)

0.001901802999782376


In [68]:
c

array([2, 2, 2, 2, 4, 4, 4, 2, 3, 3, 4, 2, 2, 2, 3, 3, 4, 2, 3, 2, 3, 2,
       3, 1, 1, 1, 3, 1, 1, 3, 3, 1, 3, 3])

In [71]:
np.where(c==2)[0]

array([ 0,  1,  2,  3,  7, 11, 12, 13, 17, 19, 21])

# Football Data

In [2]:
import sys
sys.path.insert(0, '../tests')
import helpers

In [10]:
adj_fb = (helpers.load_football()[0]).tocsr()
G_fb = nx.from_scipy_sparse_matrix(adj_fb)

loading matrix...


In [29]:
c_q = fine_tuned_clustering_q(G_fb, normalize = True, seed = 100)

In [20]:
community_set = []
for comm in np.unique(c_q):
    community_set.append(frozenset(np.where(c_q == comm)[0]))
    
community_set = set(community_set)

In [30]:
c_q

array([ 6,  9,  8,  4,  6,  6,  8,  2,  2,  6,  4,  6,  7,  8,  7,  8,  6,
        5,  7,  3,  5,  2,  2,  6,  6,  9,  7,  5,  6,  3,  3,  7,  8,  9,
        7,  3,  7,  9,  7,  8,  4,  6,  7,  7,  1,  9, 10,  8,  1, 10,  6,
        2,  4, 10,  7,  3,  5,  1, 10,  5,  8,  7,  5,  5,  8,  5,  1,  6,
        2,  6,  5,  7,  4, 10,  4,  1,  5,  2,  2,  3,  3,  4,  8, 10,  4,
        7,  1,  5, 10,  9,  6,  1,  1,  6,  3,  5,  5, 10,  4,  7,  8,  3,
        4,  9,  6,  9,  8,  4,  2,  9, 10,  2,  1,  5, 10])

In [31]:
c_qds = fine_tuned_clustering_qds(G_fb, normalize = True, seed = 100)

In [35]:
modularity_density(adj_fb, c_qds, np.unique(c_qds))

0.49436831970316597

In [36]:
modularity_r(adj_fb, c_q, np.unique(c_q))

0.5809448262776186